### PR TITLE
CELDEV-944 - add LGPL License Notice

### PR DESCRIPTION
**Pull request by fpichler**
add missing LGPL License comment to all java files.
https://www.gnu.org/licenses/gpl-faq.html#NoticeInSourceFile

cherrypick of dev-x.4 commit

### CODE REVIEW

**Review by msladek — COMMENTED** [review]
Is it legally necessary to drown every file with the LGPL license?

GitHub states [here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#determining-the-location-of-your-license):
> As a best practice, we encourage you to include the license file with your project.
> Most people place their license text in a file named LICENSE.txt (or LICENSE.md or LICENSE.rst) in the root of the repository.

If we need a license statement in every file, could we reduce it to a mere mention of the license, e.g.:
```
/*
 * This file is licensed under the terms of version 3 of the GNU Lesser General Public License.
 */
```

**Comment by fpichler** [comment]
It is best practis: https://www.gnu.org/licenses/gpl-faq.html#NoticeInSourceFile

**Comment by msladek** [comment]
I don't see any opposing statement in the provided link. My suggestion would also point to the license in case a single source file got somehow out of context.

According to my research, not having the entire license in each source file doesn't cause legal issue. Having no license in a source file could only be mistaken as no license (nonfree). Imo it only lowers the risk of someone accidentally violating your license terms.

I would therefore suggest a single license notice per repository - or at most a single line per source file.

**Comment by fpichler** [comment]
I do not get your point. I just added the notice as mentioned "best practice" on https://www.gnu.org/licenses/old-licenses/lgpl-2.1.de.html under "How to Apply These Terms to Your New Libraries". The full license is the rest of the linked page which is much more than the short added notice. Moreover every reasonable editor is collapsing the comment to one line.

I don't see any argument from you explaining why following the advice and best practis of gnu.org for applying the lgpl-2.1 license is a problem.

**Comment by msladek** [comment]
I do not see the value in adding the same 19 lines to every file in our entire codebase. GNU projects may do so as a "best practice", yet that doesn't make it necessary or even beneficial. As I already stated (all to the best of my knowledge):
- "A clear statement in the program's README file is legally sufficient as long as that accompanies the code" https://www.gnu.org/licenses/gpl-faq.html#LicenseCopyOnly
- having the statement in each source file doesn't offer extra legal protection
- if for some reason a file ends up without the accompanying license, the code has to be considered non-free anyway and cannot be simply copied (Bern Convention)

The only reason I've read for the "best practice" is if the last point isn't considered acceptable. This isn't the case for me. Do you see this differently or see benefits I've missed?

**Comment by fpichler** [comment]
The contract has two sides. Only one is about somebody taking our code and using it outside the license. The second side is that we put a product to the public and thus we can be made liable for its safty and correctness. This is the ultimate reason for the existance of the MIT license. In the event it can legally be argued that the license of a faulty part of the code was not obviously stated then the legal standard can be assumed. This legal standard makes the publisher responsible of any damage his advice/product has caused if it is not clearly and unmistakenly stated that he does not take any responsability for the published art.

In this sense it is in our interest to make clear that we cannot be made liable for the correctness of any part of the code.

-> It has been much smarter layers than me which came up with the advice to put the "license notice" in each file. And this has been done for years by now. I think we should stick to that advice and keep to the GNU best practis and put the LGPL-License-Notice in each source file as adviced. Why taking the risk and leave an uncertainty?

https://www.gnu.org/licenses/gpl-faq.html#LicenseCopyOnly clearly states: "This statement should be in each source file"

BTW: "Berne Convention" is for "Literary and Artistic Works" and does not tell anything about product liability.

**Comment by msladek** [comment]
> In this sense it is in our interest to make clear that we cannot be made liable for the correctness of any part of the code.

I don't see how adding the notice to a file offers extra legal protection for these cases. As GNU [states](https://www.gnu.org/licenses/license-list.html#NoLicense), no license would mean non-free and we cannot be made liable for code that wasn't allowed to be used in the first place.

> https://www.gnu.org/licenses/gpl-faq.html#LicenseCopyOnly clearly states: "This statement should be in each source file"

The emphasis on **should** (not must)! They even continue in the next sentence:
> A clear statement in the program's README file is legally sufficient as long as that accompanies the code, but it is easy for them to get separated. Why take a risk of [uncertainty about your code's license](https://www.gnu.org/licenses/gpl-faq.html#NoticeInSourceFile)?

Their argument for the **should** is the fallback to non-free if a source file got out of context, not that it would be legally required/benefitial.

**Comment by fpichler** [comment]
You still arguing from the copyleft/copyright perspectiv. There you make an other mistake: "non-free" does not imply that it is now allowed to be used. If it is published in the internet (on github) it can be assumed that this implies allowance for usage (if not stated otherwise). To give away at no cost does never imply no liability. In general you are also liable for gifts.

This is the difference between the discussion about copyleft/copyright and liability. For copyleft/copyright you need an explicit statement that you may redestribute. Hence if you do not know (fallback to non-free) it is not allowed. Vice versa for the liability: if not clearly stated otherwise you are liable and can be made responsible. The license notice thus explicitly point this out in the second paragraph:
"This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details."

As mentioned before: the license notice is written by lawyers and each sentence has its purpose.

Can we please just keep to the standard and not reinventing the weel again?

**Comment by msladek** [comment]
Thanks for your explanations, I don't know much about liability for source code. Yet if your assertions were the case, I don't understand why the GPL FAQ doesn't state that the notice **must** be included in every file, since the liability clauses of the license wouldn't be legally binding. Instead they explicitly state that "a clear statement in the program's README file is legally sufficient"! Thus I remain unconvinced of your argumentation unless you can point to additional sources why the GPL FAQ is wrong in this regard.

> Can we please just keep to the standard and not reinventing the weel again?

I'm not trying to reinvent a standard, I'm merely questioning the justification for the actions taken in this PR, as any action must be justified imo. The GNU project might have their best practice, this by itself isn't sufficent justification to me. I could also point to many GPL/LGPL projects that employ a different best practice. This is by no means a settled standard which a large majority of the community adheres to.

At this point, I don't want to block this PR any further. The work is already done and there is little issue in merging it. My PR approval however shouldn't be understood as agreement with the general practice.

**Review by msladek — APPROVED** [review]

**Pull request merged**
